### PR TITLE
Merge in changes from upstream master (for better or worse).

### PR DESCRIPTION
**Pull request by MTCam**

### CODE REVIEW

**Comment by MTCam** [comment]
BTW, I think we need to ignore the CI failures atm, because they'll fail even on w-hagen/master.

**Comment by w-hagen** [comment]
~~Looks like parts of the boundary conditions needed for my artificial viscosity routine got wiped out here.~~ You beat me to this comment. While the usage exterior_sol and boundary_pair need to be reworked, if the goal is just to get this upstream master changes merged in here they probably could be left as is for the moment. They are on my list to fix in the mainline [pull request](https://github.com/illinois-ceesd/mirgecom/pull/213)

**Comment by MTCam** [comment]
> ~Looks like parts of the boundary conditions needed for my artificial viscosity routine got wiped out here.~ You beat me to this comment. While the usage exterior_sol and boundary_pair need to be reworked, if the goal is just to get this upstream master changes merged in here they probably could be left as is for the moment. They are on my list to fix in the mainline [pull request](https://github.com/illinois-ceesd/mirgecom/pull/213)

Yeah, per our convo on Slack.  I inadvertently removed these in the hand-merge.  Any chance you could make sure your own tests work on this branch before we push something that breaks the hell out of it?

**Comment by w-hagen** [comment]
I will pull this branch and make sure everything is running.

**Comment by w-hagen** [comment]
> Yeah, per our convo on Slack. I inadvertently removed these in the hand-merge. Any chance you could make sure your own tests work on this branch before we push something that breaks the hell out of it?

> I will pull this branch and make sure everything is running.

Everything looks good after a few fixes to my boundary condition routines needed when updating to the latest packages.

**Comment by MTCam** [comment]
> Everything looks good after a few fixes to my boundary condition routines needed when updating to the latest packages.

Terrific, ok to merge?

**Comment by w-hagen** [comment]
Yeah, should be good.

**Pull request merged**
